name: test
on: [push]
jobs:
    test: 
        runs-on: windows-latest
        defaults:
            run:
                shell: msys2 {0}
        steps:
            - name: Setup msys2
              uses: msys2/setup-msys2@v2
              with:
                update: true
                install: >-
                    git
                    mingw-w64-x86_64-gcc
                    make
            - name: Pulling git repo
              uses: actions/checkout@v3
            - name: Test for Q2 
              run: |
                  make clean
                  make test
